### ISSUE TITLE
Avoiding future risk in signal-hook-registry's global data

### ISSUE THREAD

**Issue by erickt** [vorner/signal-hook#104]
We're updating our vendored version of signal-hook and signal-hook-registry in [fuchsia](https://fuchsia-review.googlesource.com/c/fuchsia/+/516533/6/third_party/rust_crates/vendor/signal-hook-registry/src/lib.rs#281), and we noticed some mild risk around how `GlobalData` is initialized. As best as we can tell things looks safe, but it's possible there could be some codepath down the road where a signal handler was registered before a call for `GlobalData::ensure()`. If that happened, a future call to `GlobalData::ensure()` could overwrite data being used in a signal handler and possibly trigger undefined behavior.

To avoid this risk, what do you think about using [once_cell::race::OnceBox](https://docs.rs/once_cell/1.7.2/once_cell/race/struct.OnceBox.html), which as best as I can tell is async-signal-safe since it only uses atomics. Or if you don't want to gamble on once_cell potentially becoming async-signal-unsafe, we could draw inspiration from it, and switch to something like:

```
    struct GlobalData { ... }

    static GLOBAL_DATA: GlobalCell<GlobalData> = GlobalCell {
        inner: AtomicPtr::new(),
        _phantom: PhantomData,
    };

    struct GlobalCell {
        inner: AtomicPtr<GlobalData>,
        phantom: PhantomData<Option<Box<T>>,
    }

    impl GlobalCell {
        // async-signal-safe
        pub(super) fn get(&self) -> Option<&'static GlobalData> {
             let ptr = self.inner.load(Ordering::Acquire);
             if ptr.is_null() { None } else { Some(unsafe { &*ptr }) }
        }

        // async-signal-unsafe
        pub(super) fn ensure(&self) -> &'static GlobalData> {
            let mut ptr = self.inner.load(Ordering::Acquire);
            if ptr.is_null() {
                let ptr = Box::into_raw(Box::new(GlobalData { .. }));

                let exchange = GLOBAL_DATA.inner.compare_exchange(
                    ptr::null_mut(),
                    ptr,
                    Ordering::AcqRel,
                    Ordering::Acquire,
                );

                if let Err(old) = {
                    drop(unsafe { Box::from_ptr(ptr) });
                    ptr = = old;
                }
            }

            Ok(unsafe { &*ptr })
        }
    }
```

**Comment by vorner** [comment]
Um, can you describe what the risk you're afraid actually is?

I mean, the fact that anyone trying to put anything into the data goes through the `ensure` is a core assumption. If anyone violates that, I'd say a lot more than just losing bit of data would break.

I'm not against what you propose, per se (I'd probably want to simplify it a bit ‒ instead of that exchange failing & retrying, it probably should panic ‒ the initialization is also protected by a mutex; get before initialization should probably be a hard-abort as that's a completely broken state). But I don't really see what it brings. This is one of the lesser traps in this code and one really needs to tread very carefully in here.
