### ISSUE TITLE
SIGNAL not registered immediately

### ISSUE THREAD

**Issue by yellowhat** [vorner/signal-hook#117]
Hi,
I would like run a specific function on receiving the `SIGUSR1` signal.
Consider the following example:

```rust
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

fn show() {
    let a = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_millis();
    println!("SHOW:     {}", a);
}

fn main() {

    loop {
        let term = Arc::new(AtomicBool::new(false));
        signal_hook::flag::register(signal_hook::consts::SIGUSR1, Arc::clone(&term)).ok();
        show();

        while !term.load(Ordering::Relaxed) {
            let a = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_millis();
            println!("Sleeping: {}", a);
            std::thread::sleep(std::time::Duration::from_secs(1));
        }
    }
}
```

On running:

```rust
$  cargo run
SHOW:     1636705853256
Sleeping: 1636705853256
Sleeping: 1636705854256
Sleeping: 1636705855256
Sleeping: 1636705856256
SHOW:     1636705857257
Sleeping: 1636705857257
SHOW:     1636705858257
Sleeping: 1636705858257
```

As you can see the `show()` function always run at the end of the `while !term.load(Ordering::Relaxed)` is there a way to immediatelly intercept the `SIGUSR1` signal and run the `show()` function?

Thanks

**Comment by vorner** [comment]
I'm not entirely sure what you're asking. Your code seems a bit confused, or it doesn't demonstrate exactly what you're doing. But comparing the code and the output, it seems to be behaving as expected. Let me try to explain.

The `signal_hook::flag::register` makes sure the given flag atomic variable is set to true whenever a signal comes. That happens right away, inside the signal handler. When that flag is checked is up to the application, but can't, in principle, happen right at the exact time. This pattern with the flag is most suitable when the application consists of separate tasks, it doesn't want to be disturbed during the task, but it's OK to react to signals in between. The pattern is _specifically designed_ to delay the handling until the right time. If it's not your case, you need to use a different one (more on the options below).

By the way, you register a new flag variable in each iteration of the loop. It _stays registered_ even when the loop iteration ends. That is, the flags that are no longer checked by anyone just keep accumulating in memory and make the signal handling longer and longer, because all of them need to be set.

Now, to the options you have:
* If you really need to react _right inside the signal handler_, then you can use the low-level https://docs.rs/signal-hook-registry/1.4.0/signal_hook_registry/fn.register.html. But that one is unsafe for very good reasons, as the callback registered into it is allowed to do only very limited things (exactly because it can happen at any time, on any thread). For example, using the above `show` would be UB ‒ at least `println` contains locking of a mutex or something similar. It _might_ contain allocation too. Therefore, I'd suggest to avoid that one if possible and use something else that delays the handling at some time _after_ the signal handler terminated.
* You can have a separate thread that just waits for signals to arrive. For that you can use the https://docs.rs/signal-hook/0.3.10/signal_hook/iterator/type.Signals.html to iterate over incoming signals.
* If you're using some kind of asynchronous loop, there are „adaptor crates“ ‒ signal streams that bring signal hook to eg. tokio (signal-hook-tokio, signal-hook-mio, signal-hook-async-std).

As this doesn't seem to be anything broken in signal hook, nor it is a feature request, I'll close this issue.

**Comment by yellowhat** [comment]
Thank you very much for the valuable answer.

Regarding "you register a new flag variable in each iteration of the loop.". If I put the `signal_hook::flag::register` outside the `loop {`:

```rust
fn main() {
     let term = arc::new(atomicbool::new(false));
     signal_hook::flag::register(signal_hook::consts::sigusr1, arc::clone(&term)).ok();
     loop {
        show();

         while !term.load(ordering::relaxed) {
             let a = systemtime::now()
                .duration_since(unix_epoch)
                .unwrap()
                .as_millis();
            println!("sleeping: {}", a);
            std::thread::sleep(std::time::duration::from_secs(1));
        }
    }
}
```

On sending the `SIGUSR1` signal it will loop on the `show()` function forever, that's why I redefine it every time it gets out of the `while !term.load(ordering::relaxed)` loop.


As you suggested the separate thread solution should be ideal.
I tried to reuse the example "A complex signal handling with a background thread" in this page https://docs.rs/signal-hook/0.3.10/signal_hook/index.html:

```rust
use std::io::Error;
use std::sync::Arc;
use std::sync::atomic::AtomicBool;

use signal_hook::consts::signal::*;
use signal_hook::consts::TERM_SIGNALS;
use signal_hook::flag;
use signal_hook::iterator::SignalsInfo;
use signal_hook::iterator::exfiltrator::WithOrigin;

fn main() -> Result<(), Error> {
    let term_now = Arc::new(AtomicBool::new(false));
    for sig in TERM_SIGNALS {
        flag::register_conditional_shutdown(*sig, 1, Arc::clone(&term_now))?;
        flag::register(*sig, Arc::clone(&term_now))?;
    }

    let mut sigs = vec![
        SIGTSTP, SIGCONT, SIGWINCH,
        SIGHUP,
        SIGUSR1,
    ];
    sigs.extend(TERM_SIGNALS);
    let mut signals = SignalsInfo::<WithOrigin>::new(&sigs)?;

    let mut has_terminal = true;
    for info in &mut signals {
        eprintln!("Received a signal {:?}", info);
        match info.signal {
            SIGTSTP => {
                eprintln!("SIGTSTP");
            }
            SIGCONT => {
                eprintln!("SIGCONT");
            }
            SIGUSR1 => {
                eprintln!("SIGCONT");
            }
            term_sig => { // These are all the ones left
                eprintln!("Terminating");
                assert!(TERM_SIGNALS.contains(&term_sig));
                break;
            }
        }
    }
    Ok(())
}
```

But I get:
```bash
$ cargo run
   Compiling aaaa v0.1.0 (/home/user/aaaa)
error[E0432]: unresolved import `signal_hook::iterator::exfiltrator::WithOrigin`
  --> src/main.rs:11:5
   |
11 | use signal_hook::iterator::exfiltrator::WithOrigin;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `WithOrigin` in `iterator::exfiltrator`
```

Am I missing something?

Thanks

**Comment by vorner** [comment]
You don't _redefine_ it. You register a _new one_, but leave the old one alive and registered.

As you're using the thread now, this is a bit moot, but there would generally be two solutions:
* Unregistering the old ones after they are needed.
* Resetting the flag back to false after being woken by it.

Of course with enough care to not have race conditions.
