### ISSUE TITLE
Allow explicitly ignoring signals (SIG_IGN)

### ISSUE THREAD

**Issue by Supreeeme** [vorner/signal-hook#159]
`sigaction` allows signals to be explicitly ignored with SIG_IGN, but the crate provides no way to do this.

**Comment by vorner** [comment]
You're right, because it kind of doesn't fit into the overall goal and philosophy of the crate ‒ it doesn't really expose the „raw“ signals, it tries to build some kind of sane-ish abstraction on top of that. Unless you can provide some kind of compelling reason why it _should_ (given the aim and architecture of the library), I'd prefer not to add such kind of „low level“ thing.

Nevertheless, you can still get close to this behavior ‒ you can register an effectively empty hook ‒ for example setting a flag that is never read. https://docs.rs/signal-hook/latest/signal_hook/flag/fn.register.html. You can even then unregister that hook and it'll be running an empty list of hooks.

If you still have problem with it running anything at all, I'd suspect you're doing something „out of ordinary“ and would likely prefer some kind of other library or dealing with libc directly.

**Comment by Supreeeme** [comment]
My use case is Xwayland, which will send SIGUSR1 to its process if it inherits SIGUSR1 as SIG_IGN. This is probably an unusual use case which is fine, but I don't really understand why ignoring a signal is too low level. In any case it's simple enough to do via libc.

**Comment by vorner** [comment]
Well, the core idea behind the signal-hook is that the hooks / users of the library should somehow sanely compose / co-live inside the same application. That is, one use of it should be more or less independent of another use.

This is not the case when messing _directly_ with the signal _handler_. Setting it to SIG_IGN silently disables all uses of the same signal by other parts of the application. It's a bit like using `munmap` on pages otherwise managed by malloc/free.
