### ISSUE TITLE
Document what exactly is written to pipes

### ISSUE THREAD

**Issue by datto-aparrill** [vorner/signal-hook#21]
The documentation for `signal_hook::pipe` mentions that it writes to the pipe whenever a filtered signal happens, but it never mentions exactly what is written. Is it a single byte with the signal number? A single byte of garbage? A multi-byte message?

**Comment by datto-aparrill** [comment]
Looking at the source it appears to be a single byte; `X` in ascii.

**Comment by vorner** [comment]
It's some unspecified garbage. I don't want to guarantee any *specific* value of the garbage, nor its size, only that there will be *something*.

The reason is, as described in https://docs.rs/signal-hook/0.1.10/signal_hook/pipe/index.html#write-collating, you can't rely on all the messages being written. If it was writing eg. the signal number, then some signals could be lost if they don't fit. Therefore, the only information the pipe carries is „please, wake up, *something* happened, go check it up“. What exactly happened needs to be passed out of band or implicit.

While I don't want the documentation to be cluttered with unimportant details, I'm not against documenting it. I'm at disadvantage when writing the documentation, because I already take most of the knowledge for granted, you're in a better position to know what people need to find in there. So I'd suggest you try to improve the documentation with the needed info and send a pull request :-).

**Comment by vorner** [comment]
Going to be released together with 0.1.11.
