### ISSUE TITLE
A way to restore the default signal handler?

### ISSUE THREAD

**Issue by jkarneges** [vorner/signal-hook#23]
According to the [docs](https://docs.rs/signal-hook/0.1.10/signal_hook/fn.unregister.html#warning), unregistering within the library doesn't restore the original signal handler of the process.

It is common for shutdown to be initiated by SIGTERM/SIGINT, but if a second such signal is received then force shutdown immediately. For example, a user hits ctrl-c, waits a little bit, then hits ctrl-c a second time. An easy way to implement this behavior is to restore the original signal handler after receiving the first signal. Then we just let the OS defaults handle that second signal (without risk that our own manual handling of the second signal is buggy, trapping the user). It would be nice if it were possible to do that with this library.

**Comment by vorner** [comment]
Let me first describe the problem why this is not being done, in case you see a solution I don't, and then give you a workaround for your specific problem.

I've seen several libraries to *chain* the handlers. Instead of replacing the previous handler, it remembers the handler and as part of itself, calls that. In a situation where we were registered first, then someone else did this chain to us, we can't get out of the chain correctly. We don't have access to their storage to replace whatever they call. We can't replace their handler with whatever we got as the previous one. So we just stay there, doing nothing.

You, however, don't want to return to whatever there was before signal hook registered its first signal. You want the default signal handler. So, you can just throw out everything and do `signal(signum, SIG_DFL)` (or the equivalent, I'm currently typing this from memory). This removes the whole chain. It's just, the library can't do such a drastic measure on its own.

I'd even accept pull request that implements this „drop everything, return default signal handler“ action/`register_return_to_default` functionality.

**Comment by jkarneges** [comment]
Thanks for the response, and good point. Simply overwriting the signals with SIG_DFL seems sufficient.

**Comment by vorner** [comment]
Let me reopen this and hijack the issue for supporting convenient resetting of the default handler as part of signal.
