### ISSUE TITLE
Document that `signal_hook::pipe` can *only* be used with sockets

### ISSUE THREAD

**Issue by wfraser** [vorner/signal-hook#27]
It took me a while to figure out why using an opened fifo file didn't work. My thinking was, why shouldn't it, the module is called "pipe" after all. The documentation is misleading in that it says "anything that can be sent to is fine ‒ sockets too" when in fact ONLY a socket will work, because it uses the `send` syscall. Passing any other kind of file descriptor to `send` results in `ENOTSOCK`.

**Comment by vorner** [comment]
Ups, sorry, I really thought pipes can be `sent` into too, but trying it now it turns out you're right.

The intention is that pipes really should work, only that sockets are easier to come by in Rust. So I believe the fix should be in the code, in the documentation. I'll still have to find a way to write in a non-blocking manner to the pipe, but I'm reluctant to do fcntl on it in case the fd is shared with something else (though it probably shouldn't when the methods take ownership of the thing).

I'll probably also make a „testing“ function public that does the wakeup with proper error handling (there's nowhere to put the errors when inside the signal handler, unfortunately).

**Comment by vorner** [comment]
I'll release it soon, I'm just waiting for some more branches to go through CI first.

**Comment by wfraser** [comment]
> in case the fd is shared with something else

You could always do a `dup` on it and set the duplicated FD to nonblocking so you can use `write` (this is what I'm doing in my code), but I think as you pointed out, it shouldn't be shared because you take ownership of it by taking the owning `impl AsRawFd` by value, so it should be fine to fcntl it to nonblocking without duplicating.

Anyway just updating the doc is fine! Your crate gives enough low-level access that I can implement my own weird thing. Thanks :)

**Comment by vorner** [comment]
I've already released the fix :-). And yes, I do the `dup` thing in there.
