### ISSUE TITLE
Safe signal handlers

### ISSUE THREAD

**Issue by diwic** [vorner/signal-hook#3]
Because signal handlers can't panic, can't allocate, etc, it's very difficult to write a 100% safe signal handler. 

As a brainstorming idea, how about making a struct which symbolises the most common operations? The big plus is that the caller of this library doesn't have to do anything unsafe to be able to use the library. 

Suppose we have three structs:

    pub struct WriteToFd(pub RawFd, pub &'static str);
    pub struct AbortProgram;
    pub struct IncAtomicCounter(Arc<AtomicUsize>);

...and a trait which all three implements. We'll then have some variant of the `register` function that takes one of these structs. That `register` function now no longer has to be unsafe, because all it can do is make the operations dictated by the struct, which have been thoroughly checked for panics, allocations, disallowed libc calls, etc.

**Comment by vorner** [comment]
I don't get one thing. Why is the current interface inadequate? If you don't want to write the signal handler, you can use one of the functions in submodules, eg (these are safe):

https://docs.rs/signal-hook/0.1.0/signal_hook/flag/index.html
https://docs.rs/signal-hook/0.1.0/signal_hook/pipe/index.html

In which way is it better to place a struct in between? And what role would that trait play?

Btw, when the system can consolidate multiple signals to one instance, the increment of the counter seems… not very useful.

**Comment by diwic** [comment]
> If you don't want to write the signal handler, you can use one of the functions in submodules, eg (these are safe):

Ah cool, that was the piece I was missing. 

I think there should also be a `register_write` that sends an arbitrary string to an fd, rather than just writing a (random?) byte to a pipe. One could use that to safely write to `stderr`, e g.

**Comment by vorner** [comment]
Could you expand more on what it should do? Especially in corner cases, like:

* What to do if the write would be blocking? The pipe writers try to send one byte, but if the pipe is full, it gives up ‒ because the other side will be woken up anyway (the pipe is already full). But if you want to write a string, you probably care about the content, so giving up in the middle of the string is probably a bad idea. However, blocking in a signal handler isn't a good idea either.
* What if two signal handlers run concurrently? There's a chance this will be interleaving the writes.
* Why would I want to write the same thing every time? Do you have something specific in mind?

**Comment by diwic** [comment]
Good points on the corner cases. I see you specify `MSG_DONTWAIT`, I'm not sure if you would ever end up writing half a message in that case if the buffer is just a few bytes from being full or if none of it is written. But yes, half a message is bad, regardless of whether that comes from interleaving with another signal handler or pipe being full.

So I was thinking first "quick and easy debug" by writing the string "I got SIGTERM, quitting program!\n" (or similar) to stderr. In which case interleaving happens so rarely that you can probably live with it. 

But given a reasonably big pipe (64K buffer or whatever the standard size is) and writing only one byte because larger writes might be cut in half, it is extremely unlikely it gets full to the point that we lose signals. In that case, what stops us from having one receiver fd for more than one signal, except the fact that you seem to write `b"X"` for all of them? Why not distinguish different signals by writing different letters on the pipe? It seems like a waste of fds to me to have one fd for each signal?

**Comment by vorner** [comment]
Yes, in `MSG_DONTWAIT` you'd get a short write. Actually, if the buffer was close to being full, but not completely yet, you'd get a short write from any write/send (more specifically, no matter what, you can get a short write or short read for many different reasons). The `std::io::Write::write_all` handles a lot of that, but I'm reluctant to use that inside a signal handler.

So the solution would either be somewhat broken or complicated (likely both). I'd rather avoid it having here, because that would promote such solution. But there's the possibility of having another crate that just uses the low-level registration, or if it's just for a debug and it would go away, writing the unsafe handler yourself knowing it is probably broken, but that it will go away before production.

The default size of a pipe is configurable somewhere in sysctl. And even though filling it up might be unlilkely, so is probably hitting one specific lock and getting a deadlock. In that sense, relying on unlikelies is something I don't want to do. If I distribute a million copies of the code, every unlikely thing will happen sooner or later. I prefer the attitude „if something can possibly go wrong, it will“.

But I see where you're coming from with the waste of fds ‒ that's why the thing  in the `iterator` module is composed of a single fd and a set of `AtomicBool` flags ‒ the pipe wakes up and the receiving end examines the flags to decide what signals happened.

**Comment by vorner** [comment]
No concrete ideas what safe abstractions to add here in this ticket, so I'm going to close this for now. If there are some specifics, I'll be glad for other issues or pull requests.
