### ISSUE TITLE
Move async support to separate crates

### ISSUE THREAD

**Issue by tfkhim** [vorner/signal-hook#39]
As discussed in pull request #37 the async support for different runtimes should not be part of the base signal-hook crate. So I wrote down my thoughts about this so we can agree upon requirements and an approach.

**General goals of the change**

1. No code changes required for client code of Signals which doesn't use async features yet. This means the public types Signals, Pending and Forever must stay the same from a
client code perspective:
    * Type signature must stay the same so client code with explicit types like ```let sigs : Signals = ...``` still works
    * Implementation and private members may change
    * Methods must accept the same arguments and have the same return types
2. Add a meaningful API to allow:
    * Implementing support for major async runtimes in separate crates
    * Implementing mio support in its own crate

**Acceptable breaking changes**

* Client code using the existing async features must be updated

**Outline of the approach I would like to try**

Instead of pulling out the UnixStream file descriptor I would like to abstract over the IO type used for the pipe. The reason for this is that not all runtimes (e. g. async-std) provide a way to register an arbitrary file descriptor. But all runtimes offer their own async wrapper for UnixStream. A high level outline:

* Use generic types for write and read ends in Waker and Signals
* Add traits SelfPipeWrite and SelfPipeRead for the two pipe ends
    * SelfPipeWrite offers the non blocking wake() method to write something to the pipe
    * SelfPipeRead offers a non-blocking flush() method to clear the pipe contents
* Signals and Waker use the methods provided by these traits
* Implementations for std::os::unix::net::UnixStream will provide the same functionality as today
* Make the Forever struct more general in the sense that it should support both blocking and non-blocking use cases. Using this generalization we can then implement:
    * Iterator trait for blocking pipe types
    * Stream trait (Future 0.1.x and Future 0.3.x) for non-blocking pipe types

**Benefits of this approach**

* Support for async-std without assuming it is using smol
* Allows sharing of code between the current Forever and Async implementations which are quite similar
* Allows using other pipe like IO types as well

@vorner  Do you have any requirements / goals to add? Can I give this approach a try or do you have any concerns?

**Comment by vorner** [comment]
Hello

Thanks for the extensive writeup. My thoughts:

* No changes for sync-only users is probably only soft requirement ‒ it's nice if it can be done that way. But if a small breaking change needs to be done to make it work or because otherwise the code would be unnaturally convoluted, I think it is fine. If we remove the async parts, the crate will have to go to the 0.2 anyway.
* I am not sure if going with the special traits (`SelfPipeWrite` and `SelfPipeRead`) is necessary or if it brings much added value compared to the added complexity. Furthermore, one would need to document well what properties such pipes need to have in terms of signal safety, blocking, allocations, etc. I'm not saying not to use them, but I'd propose also considering some more light-weight approach such as being able to create `Signals` from a file descriptor passed *into* it. Hopefully, if `async-std` provides some UnixStream of its own, it would be possible to convert that one into a file descriptor. Consider it a kind of vague brain-storming.

But yes, overall it looks good, feel free to give it a try :-). If you want me to have a look and discuss code somehow in the middle of the progress, I'm fine with it.

**Comment by vorner** [comment]
May I inquire on your progress? I don't want to press you, just wanting to keep track of what stands where :-)

**Comment by tfkhim** [comment]
Hi,

I'm still onto it. I couldn't make progress as fast as I'd like to. But in the next few days I should be able to share a version which should give you an impression of how things will look like in the end.

**Comment by tfkhim** [comment]
I pushed my current version to the [async-extract branch of my fork](https://github.com/tfkhim/signal-hook/tree/async-extract).

The branch contains the refactoring of the basic structs to support blocking and asynchronous UnixStream pipes from different runtimes. The split into multiple crates isn't there yet. But I already changed the Tokio and MIO support code to use only public parts of the API to ensure the split can be performed.

The only test cases which needed changes are the Tokio support tests. I think this is a good sign that client code doesn't have to change a lot.

**Small roundup of the most important changes:**

- The Waker, Signals and Forever structs now support generic read and write IO types.
- I followed your suggestion and droped my initial SelfPipeRead and SelfPipeWrite idea. The Signals struct can be created from IO types which implement the AsRawFd trait and support send and recv for the returned file descriptor.
- Pending is no longer bound to the lifetime of the Signals instance but owns a clone of the Arc<Waker> and uses an usize member to implement the Iterator trait. This allows for the Forever implementation to be used in the Tokio runtime support.
- The Forever::next_signal method allows the implementation of blocking Iterator and asynchronous Stream traits by using different has_more callbacks.

**There are some things I'm not happy with:**

- The with_pipe and next_signal methods have to be public members of the Signals and Forever implementations. But those shouldn't be used by normal users and are also one level of abstraction below the other methods. So they just pollute the otherwise nice, minimal and clean API.
- The next_signal may need a better name: maybe poll_signal
- The MIO support implementation isn't really nice. Doing it proper would require a way to get a reference to the read end from the Signal struct. But adding such a method to Signals would just pollute the API even more and add more ways for users to shoot theirself in the foot.

I think about moving the low level parts (which have to be public for reuse in the adapter crates) into a backend module. This would make the separation between the high level API and adapter support API more clear. Adding there a method to get a reference to the read end for clean MIO support seem reasonable to me. I didn't want to do this without asking for your opinion.

I'm curious about your thoughts.

**Comment by vorner** [comment]
Thanks. I'll have a look as soon as I can, but right now I have some personal things to deal with, so it might have to wait maybe until next week.

**Comment by vorner** [comment]
I've read through the changes and feel this is turning out really nice, good job :-).

There are still some things I'd like to discuss, though.

# Signals and type parameters

The `Signals` structure is meant to be the „I don't want to deal with details, give me something convenient“ level of API. I feel like adding type parameters to than goes a bit against that goal (it isn't an issue if you just keep it in local untyped variable, but if you want to store it in some bigger data structure, it now becomes an inconvenience).

Furthermore, I wonder how the various methods will behave if wrong types are passed there. Things like „Does it make sense to have different read & write ends?“ come to mind. What happens if I do `Signals<File, File>`?

One option would be to use default type parameters on the struct so one doesn't have to deal with it unless doing something out of ordinary.

But also considering also the API pollution problem, I'd think the split into backend (that has type parameters and all kinds of `.next_signal` and `.with_pipe` methods, but not the high level iterator stuff, hidden somewhere in a submodule or just `crate::iterator::Backet`) and frontend (the current `Signals`) is actually a very good idea.

Related to that, I wonder if it makes sense at this point to put `R/W` in the Waker, or just file descriptors (or the OwnedFd from the pipe module) to get rid of the generics; I don't have a strong opinion on that one, I'm just thinking aloud here.

# Error handling, iteration, ...

I've noticed few things that made me stop at the place. One of them is the thing with ignoring of errors is suspicious. Could this lead to a tight infinite loop, spinning by always getting an error (EOF, or by having a file descriptor that can't be read from ‒ it's now possible to feed arbitrary FD into the thing), finding no signals and retrying?

Shouldn't the iteration use `signals.wait` internally for blocking? Or pass the callback all the way into the wait? I kind of don't really like the code duplication around that part.

I'm also not 100% sure if the callback to detect if the FD is readable is the best API ‒ it feels like exposing too many details and callback-based APIs in rust often tend to turn out a bit awkward due to ownership rules (that's while in C you'd do async with callbacks but Rust had to go with futures). But I don't have a better alternative in mind right now and this is going to be used only internally/by implementers of integrations to various runtimes, so it's probably good enough and investing few months discussing the best API is not worth it.

# Mio implementation

Should it put mio-uds there instead, now that we can change the type of „pipe“ inside?

# Various tiny inconsequential nitpick

Which I'm throwing in anyway when I've already looked at the code 😇.

I tend to prefer (I think clippy suggested that to me some time ago, maybe it still does) the use of `Arc::clone(&xyz)` instead of `xyz.clone()`. Most clones are „deep“ and when reading that, one expects both expensive operation and getting a value that is independent. The `Arc` acts differently and I like to see it in the code right away.

There's a comment about some value not possible to be returned in `Forever::next`. Instead of comment (or in addition to it), can there be an assert? Like instead of `if let Ready(Some(_)) = ` have:

```rust
match ... {
    Ready(Some(_)) => ...
    Ready(None) => ...
    _ => unreachable!("In blocking mode we can't not be ready because..."),
}
```

Not that I wouldn't trust the current code now, but it might get refactored in the future and I feel like one can't be careful enough.

Should `forever` take `self` instead of `&self` and cloning inside? It won't end until done with anyway and the user can clone it if they like (which would be mostly rare).


Once again, thank you for working on this. And don't be put off by the amount of comment I can produce, it's not about your code not being up to the standard, it's about me being a perfectionist. I produce a lot of them every time I read some code 😇.

**Comment by tfkhim** [comment]
A small status update: I'm working on an updated version with the backend separation. I'll try to address your other proposals as well in the progress.

For your thought about the R/W in waker: While it doesn't bother me too much in the waker struct I don't like that it is also leaking into the Pending structure. The pending struct just needs the vector of atomic booleans and doesn't use the read and write halfs of the pipe. So exposing the R and W type in Pending is useless and confusing. Having a generic free waker would remove this, too.

Thanks for the hint with the MIO UnixStream types. Makes sense to me, too.

The callback is due to a future adapter for new style Futures and AsyncRead. There will be a reference to Context in the  poll_next method which must be passed through the next_signals method into the AsyncRead::poll_read method of the read pipe end. A clousure was the simplest approach I could think of to accomplish that.

I hope to share an updated version soon.

**Comment by vorner** [comment]
> Having a generic free waker would remove this, too.

One more random thought. Could the Waker be made into some kind of trait object? It's already inside Arc everywhere so it could be something like `Arc<dyn Waker>` and having `WakerImpl<R, W>` as the actual implementations.

**Comment by tfkhim** [comment]
You can find an updated version in my fork [async-extract](https://github.com/tfkhim/signal-hook/tree/async-extract).

Finally the async support is now part of the signal-hook-mio, signal-hook-mio-0_6 and signal-hook-tokio_0_1 crates. After introducing the backend module, client code shouldn't be able to tell any difference compared to the the current master.

For removing the generics from the Pending structure I put the flag vector inside an Arc. This way it's possible to get a shared reference to the flags without having to clone the whole Waker struct. Storing only plain file descriptors may require more unsafe code and we may miss some of the behavior defined in the drop() method of the IO types. On the other side: Introducing a new trait just for the purpose of removing the generics from Pending felt a bit heavy.


Your idea of moving the callback into the wait method allowed for a nice reuse of this method in the Forever implementation. I also moved the error handling up to the callers instead of ignoring errors in the callback. At the moment I decided to panic in the event of an error so the API keeps the same. But passing the errors to the client code is an option, too.

**Some random thought of mine**

As far as I can see there aren't many use cases for cloning the Signals struct. Especially because results will be random when cloning Signals instances and querying them from multiple threads. The most important use case I see is closing the Forever iterator or returning from the wait method early.

I would propose to remove cloning from the Signals struct and add a way for getting some CloseHandle which offers the close() method. CloseHandle must be Send and may be Clone as well.

This way it would be possible to store the reading pipe half outside of an Arc which would at least make the mio Source implementation simpler. But other implementation details may profit by this as well. It would also reduce the complexity of the closing mechanism because there can be at most one thread reading from the pipe. Yes, I'm looking at you flush() who has to write something to the pipe if in closed state ;-)

But this would be a rather big breaking change in the API. And I'm not sure if there are other use cases I'm not aware of.

**Comment by vorner** [comment]
Thanks. Right now I'm at a place without too much Internet so I can't promise if I'll get to it this weekend or the next one, but I'm keeping it in mind :-).

Would you mind creating a pull request for it? It might be easier to put comments on the code.

**Comment by tfkhim** [comment]
No hurry, take your time. I created a pull request.

There are some problems in the Travis CI tests. I'll take a look at this.

**Comment by vorner** [comment]
Do you want to keep this open for tracking the support for other runtimes, or should this be closed? If you want to track it, do you think you could put the remaining things as checkboxes into the first comment, so we can see what's still left?

**Comment by tfkhim** [comment]
I think we can close this one. I can keep track of the remaining things in my head :)
