### ISSUE TITLE
How can i catch a panic?

### ISSUE THREAD

**Issue by chertov** [vorner/signal-hook#46]
I have an application that starts external process via __tokio::process::Command__
it works on armv5 with __armv5te-unknown-linux-gnueabi__ target
i can't get a full debug backtrace, but error is:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/signal-hook-registry-1.2.0/src/lib.rs:293:43
stack backtrace:
   0: 0xb69e4934 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3f629828684d5dbe
   1: 0xb6a0d0ac - <unknown>
   2: 0xb69dfa24 - <unknown>
```
How can i catch it?

**Comment by vorner** [comment]
First of, you don't catch panics. Panics are bug reports that something is rotten. Technically, it's *possible* to catch them (see the `std::panic` module), but you really don't want to.

But if you look at the code that panicked, this is because ‒ for reason that is unknown to me ‒ the OS passed NULL as the siginfo parameter, or something else hijacked the signal and doesn't pass it around.

I don't know what happens there, if it's some kind of kernel bug or interaction with another library that plays with signals. But that thing really should not be NULL. Can you get an `strace` of the run? That one could help.

**Comment by chertov** [comment]
Thank you! the application runs on top of uclibc 0.9.8 and old kernel 3.0.8 with сhinese patch. it's an ip camera.
Rust doesn't have uclibc target, but armv5te-unknown-linux-gnueabi works good in most use cases. I think problem is here. My temporary solutions is to comment signals from lines
```signal::sigaction(..., &sig_action)```
and now application do not panic
I will try to dump strace output

**Comment by chertov** [comment]
I can't get an error under strace.. it is working 2 hours without a panic

I know on normal system we don't get a panic, but in my use case the bad environment kills an application
It is a bad way to avoid an error, but i can't find a solution how to catch this error in main thread.. my little hack is working
```
if let Some(info) = unsafe { info.as_ref() } {
    for action in slot.actions.values() {
        action(info);
    }
} else {
    println!("Can't get siginfo_t for signal: {}", sig);
};
```
```
Can't get siginfo_t for signal: 17
```
17 is SIGUSR2
the command __killall -SIGUSR2 rust__ has good info.as_ref() is Some(info), but sometimes i get a SIGUSR2 info.as_ref with None

Can you to change the code to avoid unwrap() in extern "C" function or maybe other way to catch it?

**Comment by vorner** [comment]
I don't think there's a good enough solution for your problem that could be put into the library. As you've noted yourself, what you did is not really a production-ready solution ‒ in case such signal comes, it is just silently ignored which is definitely wrong. The signal did come, so library as this must propagate it.

But to call the action, I need the structure. As having it not set seems to be really illegal from the reading of man pages, changing the type of the parameter to `Option<_>` seems wrong ‒ on any working platform this just can't happen and the signature should reflect that. Furthermore, that would require bumping major version, which would create a lot of churn, not to mention the fact that this particular library just isn't designed to be present multiple times in multiple versions in the dependency graph.

One could arguably stub the structure by having a zeroed-out one to pass around, but doing that silently is also a big hack that could break someone's code silently in case something goes wrong, so I'm reluctant to do that too without knowing more about what happens there.

But you're right that panicking in that signal handler is really wrong too. So it seems what the library should do is aborting instead of panicking, which is at least not UB (caused by the caller‒libc not upholding the contract). I'll do that, but I have the impression this won't help you with your problem.

To clarify, I'm OK with having some workarounds for specific platforms, if it is some consistent quirk and doesn't break stuff for others. There's, for example, some specific handling for android. So if there's a way to detect the quirk (not just by missing the argument, but also having some well-defined way to tell *why* it is missing) and it is something common, then we can do something about that.

But if it is just some random broken patch that sometimes sends lame signals, I don't think this library should handle it in upstream. What you can try, though, is:

* Find out when and why the parameter is missing. I don't know if you tried the strace on the platform itself. I wonder if that NULL thing comes from the kernel or from uclibc or where.
* Ask the vendor to fix it (if you manage to find out it's their fault). The `siginfo_t` and such seems to come from some POSIX standard version. But from my experience, asking these vendors to adhere to standards is… tricky business.
* Integrate with the platform in some less hacky way. It is possible some constants passed around to the libc don't match (that the value of a `#define` is different between the uclibc and glibc or that even it is different on that particular platform). Either compiling for the `-musl` target (that would create a fully static binary not depending on the platform uclibc) or going the way of compiling your own copy of standard library and libc crate to compile against the right headers could help in such case.
* You could keep your own fork with some hack like the above (or better, with the stubbed-out struct).

**Comment by vorner** [comment]
I think whatever can be done about it in the library has been done. If you can provide more information about what and why happens at that platform or come up with a better idea what to do about it, feel free to reopen.

**Comment by chertov** [comment]
@vorner thank you for the detail explanation!
I could not find out exactly the reason why i get a null ptr sig_action.
I can't use static musl toolchain because my rust application depends on Hisilicon SDK *.so libraries, and they are builded for uclibc 0.9.8.
I am using a little patch to avoid unwrap() and keep it behind rustlang cargo feature "do_not_panic_in_extern_fn". I think this is an acceptable solution for my use case.
