### ISSUE TITLE
Missing WithOrigin

### ISSUE THREAD

**Issue by tal-zvon** [vorner/signal-hook#93]
New to Rust. Checking out the signal-hook crate.
Using `signal-hook = "0.3.4"`.

As far as I can tell, in docs.rs, `WithOrigin` is a struct that is defined here:

signal_hook::iterator::exfiltrator::origin::WithOrigin

And re-exported here:

signal_hook::iterator::exfiltrator

which is why in the example [here](https://docs.rs/signal-hook/0.3.4/signal_hook/index.html#a-complex-signal-handling-with-a-background-thread), it is imported as `use signal_hook::iterator::exfiltrator::WithOrigin;`. So far, makes sense.

When I try to follow the same example in my own project however, I get `could not find 'origin' in 'exfiltrator'`.
If I do `cargo doc --open` and search for "WithOrigin", I get 0 results.

To be clear, if I copy and paste the example into my main.rs, and have the `signal-hook = "0.3.4"` line in my Cargo.toml, it will NOT compile because of the missing `WithOrigin`.

I don't know how it can be possible that it exists in docs.rs, but not in my local version that cargo downloaded, even though both the local version, and the one on docs.rs are 0.3.4.

**Comment by vorner** [comment]
It's behind a feature flag you have to turn on: https://github.com/vorner/signal-hook/blob/master/src/iterator/exfiltrator/mod.rs#L14

So you'll put something like: `signal-hook = { version = "0.3.4", features = ["extended-siginfo"] }` into Cargo.toml.

Does that help? If so, you can close this 😇.

**Comment by tal-zvon** [comment]
Thanks - I'll give it a try.

This seems like something that might need to be mentioned on the front page, along with the example, as the example doesn't compile, or mention anything about `extended-siginfo`, and the compiler doesn't make it obvious why this doesn't work either.

**Comment by vorner** [comment]
Good point. I thought I've had that section there, but I must have lost it when trying to clean the documentation up. I'll re-add it.

I've also tried to add these fancy blue feature-flag labels, like for example tokio has in the documentation, but for some reason they didn't appear and it takes a release for each try, so I haven't pursued it :-|.

**Comment by tal-zvon** [comment]
Confirmed that your suggestion fixed the issue. Thanks!
I'm sure lots of beginners like me will appreciate the note in the documentation. Thanks for that as well.

**Comment by follower** [comment]
Can I suggest re-opening this issue because AFAICT there's still no documentation about this requirement in the README: https://github.com/vorner/signal-hook/blob/e3b99c41495b0b801fa29c2dfaa455c80a1d220f/README.md

Additionally, the example code refers to `App` which also doesn't exist.

I'm guessing this is because it's based on this doc example: https://github.com/vorner/signal-hook/blob/b08e6cf55f552e7e852c70a23620574641c281f2/src/lib.rs#L203-L316

That example "hides" the `App` definition here: https://github.com/vorner/signal-hook/blob/b08e6cf55f552e7e852c70a23620574641c281f2/src/lib.rs#L223-L232

I was able to get this first doc example working: https://github.com/vorner/signal-hook/blob/b08e6cf55f552e7e852c70a23620574641c281f2/src/lib.rs#L181-L201

May I suggest that it might be a good idea to start with this more basic example in the README?

**Comment by vorner** [comment]
Well, I understand README as kind of showcase, not really proper documentation. For that it should not flood the reader with huge amount of information, especially generic information that one might need to enable a feature to get some functionality or other.

So you're right the shorter example is probably more in place for README (and I've replaced that), but I don't think it's proper to explain what features are or including the definition of dummy application placeholder.

**Comment by tal-zvon** [comment]
@vorner Sounds reasonable to me. For anyone looking for a deeper explanation, with more advanced examples, they can have a look at the docs, or the article I wrote back when I was trying to figure this out: https://dev.to/talzvon/handling-unix-kill-signals-in-rust-55g6
