### ISSUE TITLE
`emulate_default_handler` always seems to abort on Linux

### ISSUE THREAD

**Issue by jonas-schievink** [vorner/signal-hook#97]
```rust
use std::sync::{
    atomic::{AtomicBool, Ordering},
    Arc,
};

use signal_hook::consts::SIGINT;

fn main() {
    let flag = Arc::new(AtomicBool::new(false));
    let id = signal_hook::flag::register(SIGINT, flag.clone()).unwrap();

    println!("press Ctrl+C");
    while !flag.load(Ordering::Relaxed) {}

    signal_hook::low_level::unregister(id);
    signal_hook::flag::register_conditional_default(SIGINT, flag).unwrap();

    println!("press Ctrl+C again");

    loop {}
}
```

This program always results in the following:

```
press Ctrl+C
^Cpress Ctrl+C again
^Cfish: “cargo run” terminated by signal SIGABRT (Abort)
```

I would expect it to be terminated with SIGINT, not SIGABRT, since I just pressed Ctrl+C.

**Comment by vorner** [comment]
Indeed, that seems like a bug. Do you want to have a look at what's happening, or or do you want to wait until I get around to it?

According to a quick strace it seems the signal is masked at the time… possibly because it is inside the signal handler for it. Unmasking it might do the trick

(The abort is a fallback if sending the original signal doesn't work)

**Comment by jonas-schievink** [comment]
It's not terribly urgent, so I probably won't look into it soon
